const RESPONSE_EXAMPLE = {
  totalCount: "3260",
  listCount: 45,
  list: [
    {
      channelName: "개이득",
      title: "노아 AI, 뷰트랩(viewtrap) | 심플 무료 버전",
      publishedTime: 1,
      viewCount: 16944,
      browseId: "UCaHMzuTxdZ7QH1L-OEbaDsQ",
      videoId: "W0al4fsBNTg",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/zRlo13AT3zw24j-qsqw46dtw-ruH_-tcYHZMhkPfKbvLdGr89s6W-Hqb7LNfx-gLHFJSXqQe=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 425,
      id: 20,
      point: 39.868,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "개이득",
      title: "노아 AI, 뷰트랩(viewtrap) | 심플 무료 버전",
      publishedTime: 1,
      viewCount: 16944,
      browseId: "UCaHMzuTxdZ7QH1L-OEbaDsQ",
      videoId: "W0al4fsBNTg",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/zRlo13AT3zw24j-qsqw46dtw-ruH_-tcYHZMhkPfKbvLdGr89s6W-Hqb7LNfx-gLHFJSXqQe=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 425,
      id: 20,
      point: 39.868,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "개이득",
      title: "노아 AI, 뷰트랩(viewtrap) | 심플 무료 버전",
      publishedTime: 1,
      viewCount: 16944,
      browseId: "UCaHMzuTxdZ7QH1L-OEbaDsQ",
      videoId: "W0al4fsBNTg",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/zRlo13AT3zw24j-qsqw46dtw-ruH_-tcYHZMhkPfKbvLdGr89s6W-Hqb7LNfx-gLHFJSXqQe=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 425,
      id: 20,
      point: 39.868,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "개이득",
      title: "노아 AI, 뷰트랩(viewtrap) | 심플 무료 버전",
      publishedTime: 1,
      viewCount: 16944,
      browseId: "UCaHMzuTxdZ7QH1L-OEbaDsQ",
      videoId: "W0al4fsBNTg",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/zRlo13AT3zw24j-qsqw46dtw-ruH_-tcYHZMhkPfKbvLdGr89s6W-Hqb7LNfx-gLHFJSXqQe=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 425,
      id: 20,
      point: 39.868,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "개이득",
      title: "노아 AI, 뷰트랩(viewtrap) | 심플 무료 버전",
      publishedTime: 1,
      viewCount: 16944,
      browseId: "UCaHMzuTxdZ7QH1L-OEbaDsQ",
      videoId: "W0al4fsBNTg",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/zRlo13AT3zw24j-qsqw46dtw-ruH_-tcYHZMhkPfKbvLdGr89s6W-Hqb7LNfx-gLHFJSXqQe=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 425,
      id: 20,
      point: 39.868,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "개이득",
      title: "노아 AI, 뷰트랩(viewtrap) | 심플 무료 버전",
      publishedTime: 1,
      viewCount: 16944,
      browseId: "UCaHMzuTxdZ7QH1L-OEbaDsQ",
      videoId: "W0al4fsBNTg",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/W0al4fsBNTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDYzJNv0MmkfvdMthJdyPAtcNEc3w",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/zRlo13AT3zw24j-qsqw46dtw-ruH_-tcYHZMhkPfKbvLdGr89s6W-Hqb7LNfx-gLHFJSXqQe=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 425,
      id: 20,
      point: 39.868,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
    {
      channelName: "모얼포스트",
      title: "워드프레스, 티스토리 아직도 속으실 건가요?",
      publishedTime: 3,
      viewCount: 2572,
      browseId: "UCCJBzmnxeadp0U4q2eCMXSw",
      videoId: "ORw2vsVWF9o",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAY3s2NyZQWWaqP03N8FR0WjlvklQ",
          width: 360,
          height: 202,
        },
        {
          url: "https://i.ytimg.com/vi/ORw2vsVWF9o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDTwjOxb8yL4mG1645qgBp1xhPIEw",
          width: 720,
          height: 404,
        },
      ],
      channelThumbnail: {
        url: "https://yt3.ggpht.com/rTof-fqu9-9BUWEJBhdM-Ft0vI-Sr4J6YVCFwL69erNvjQ13nzFqM9b7LZrxdKwbdOeijybY=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      subscribers: 29,
      id: 0,
      point: 29.563,
    },
  ],
};

export { RESPONSE_EXAMPLE };
